import { Inter } from 'next/font/google'
import './globals.css'
import Header from './common/layouts/header/Header'
import Footer from './common/layouts/footer/Footer'

import { ThemeProviders } from './common/theme/ThemeProvider'
import { NextIntlClientProvider, useMessages } from 'next-intl'

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//     title: 'Create Next App',
//     description: 'Generated by create next app',
// }

export default function RootLayout({
    children,
    params: { locale },
}: {
    children: React.ReactNode
    params: any
}) {
    const messages = useMessages()
    return (
        <html lang={locale} className="light">
            <body className={inter.className}>
                <NextIntlClientProvider locale={locale} messages={messages}>
                    <ThemeProviders>
                        <Header />
                        <div className="min-h-screen">{children}</div>
                        <Footer />
                    </ThemeProviders>
                </NextIntlClientProvider>
            </body>
        </html>
    )
}
