import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/app/globals.css'
import CommonProvider from '../provider/CommonProvider'
import { NextIntlClientProvider, useMessages } from 'next-intl'
import AuthProvider from '../provider/SessionProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
    params: { locale },
}: {
    children: React.ReactNode
    params: any
}) {
    const messages = useMessages()

    return (
        <html lang={locale} className="light" suppressHydrationWarning>
            <body className={`${inter.className}`}>
                <NextIntlClientProvider locale={locale} messages={messages}>
                    <AuthProvider>
                        <CommonProvider>{children}</CommonProvider>
                    </AuthProvider>
                </NextIntlClientProvider>
            </body>
        </html>
    )
}
